/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by drizzle-zero.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { Row } from "@rocicorp/zero";
import { createBuilder } from "@rocicorp/zero";

const accountTable = {
  name: "account",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    providerAccountId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "provider_account_id",
    },
    providerId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "provider_id",
    },
    userId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "user_id",
    },
    access_token: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    refresh_token: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    id_token: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    access_token_expires: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    refreshTokenExpiresAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "refresh_token_expires_at",
    },
    scope: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    password: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
} as const;
const activitiesTable = {
  name: "activities",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    description: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    kudos: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    start: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    elapsedTime: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    movingTime: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    type: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    elevation: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    distance: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    visibility: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    summaryPolyline: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    startCoords: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    endCoords: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    updatedAt: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
  },
  primaryKey: ["id"],
  serverName: "activity",
} as const;
const userTable = {
  name: "user",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    email: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    emailVerified: {
      type: "boolean",
      optional: true,
      customType: null as unknown as boolean,
      serverName: "email_verified",
    },
    image: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
} as const;
const userRelationships = {
  provider: [
    {
      sourceField: ["id"],
      destField: ["userId"],
      destSchema: "account",
      cardinality: "one",
    },
  ],
} as const;
/**
 * The Zero schema object.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const schema = {
  tables: {
    account: accountTable,
    activities: activitiesTable,
    user: userTable,
  },
  relationships: {
    user: userRelationships,
  },
  enableLegacyQueries: true,
  enableLegacyMutators: true,
} as const;

/**
 * Represents the Zero schema type.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Schema = typeof schema;
/**
 * Represents a row from the "account" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Account = Row<typeof accountTable>;
/**
 * Represents a row from the "activities" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Activity = Row<typeof activitiesTable>;
/**
 * Represents a row from the "user" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type User = Row<typeof userTable>;

/**
 * Represents the Zero schema query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const builder = createBuilder(schema);
